---
apiVersion: v1
kind: Namespace
metadata:
  name: queue
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: rabbitmq
  namespace: queue
spec:
  interval: 1m
  url: https://github.com/vajeen/helm
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include rabbitmq dir
    !/charts/rabbitmq
    # exclude README from rabbitmq dir
    /charts/rabbitmq/**/*.md
  values:
    image:
      registry: 588412678986.dkr.ecr.eu-west-1.amazonaws.com
      repository: oneflow-rmq/bitnami/rabbitmq
      tag: 3.11.2-debian-11-r2
    replicaCount: 2
    tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "queue"
      effect: "NoSchedule"
    podAntiAffinityPreset: hard
    ingress:
      enabled: true
      path: /*
      pathType: ImplementationSpecific
      hostname: queue.sandbox.flowdev.se
      ingressClassName: "alb"
      annotations:
        alb.ingress.kubernetes.io/tags: Environment=sandbox
        alb.ingress.kubernetes.io/group.name: internal
        alb.ingress.kubernetes.io/group.order: '97'
        alb.ingress.kubernetes.io/target-type: 'ip'
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    extraVolumes:
    - name: secretvol
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: aws-secrets
    extraVolumeMounts:
    - name: secretvol
      mountPath: /mnt/secret
      readOnly: true
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::588412678986:role/secretsmanager_csi_iam_role
    auth:
      username: admin
      existingPasswordSecret: rabbitmq-password
      existingErlangSecret: rabbitmq-erlang-cookie
    persistence:
      size: 20Gi
    memoryHighWatermark:
      enabled: true
      value: 0.8
    resources:
      limits:
        memory: 3Gi
