---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: queue
spec:
  provider: aws
  secretObjects:
  #checkov:skip=CKV_SECRET_6:Base64 High Entropy String
  - secretName: rabbitmq-password
    type: Opaque
    data:
    - objectName: rabbitmq-password
      key: rabbitmq-password
  #checkov:skip=CKV_SECRET_6:Base64 High Entropy String
  - secretName: rabbitmq-erlang-cookie
    type: Opaque
    data:
      - objectName: rabbitmq-erlang-cookie
        key: rabbitmq-erlang-cookie
  parameters:
    objects: |
      - objectName: rabbitmq-admin
        objectType: secretsmanager
        objectAlias: rabbitmq-password
      - objectName: rabbitmq-cookie
        objectType: secretsmanager
        objectAlias: rabbitmq-erlang-cookie
